# Generated by Django 4.2.20 on 2025-04-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50)),
                ('resolution', models.DecimalField(decimal_places=1, max_digits=4)),
                ('aperture', models.CharField(max_length=10)),
                ('sensor_type', models.CharField(max_length=50)),
                ('flash', models.CharField(max_length=50)),
                ('features', models.TextField()),
                ('video_resolution', models.CharField(max_length=20)),
                ('number_of_cameras', models.IntegerField()),
            ],
            options={
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('color_rgb', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Screen_resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'screen_resolution',
            },
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(max_length=50)),
                ('firmware', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'so',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('storage', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.brand')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phone.camera')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.color')),
                ('screen_resolution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phone.screen_resolution')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phone.so')),
            ],
            options={
                'db_table': 'phone',
            },
        ),
    ]
