# Generated by Django 4.2.20 on 2025-04-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_rgb',
            new_name='color_hex',
        ),
    ]
