# Generated by Django 4.2.20 on 2025-04-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_rename_color_rgb_color_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.camera'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.screen_resolution'),
        ),
    ]
