# Generated by Django 4.2.20 on 2025-04-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.rol')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
