# Generated by Django 4.2.20 on 2025-04-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user.rol'),
        ),
    ]
