# Generated by Django 4.2.20 on 2025-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_rol'),
    ]

    operations = [
    ]
